### ISSUE TITLE
【调查问卷】微信支付 API v3 PHP SDK 开发者体验调查

### ISSUE THREAD

**Issue by xy-peng** [wechatpay-apiv3/wechatpay-php#17]
为了向广大开发者提供更好的使用体验，我们诚挚邀请您将使用微信支付 API v3 SDK中的感受反馈给我们。本问卷可能会占用您不超过2分钟的时间，感谢您的支持。

问卷地址，请点击[这里](https://wj.qq.com/s2/8779987/8dae/)。你也可以扫描以下二维码参与调查。

![image](https://user-images.githubusercontent.com/1812516/126434257-834ef6ab-e66b-4aa2-9104-8e37d7a14b93.png)

**Comment by zouum** [comment]
**调用V3接口查询使用子商户支付的订单的时候，抛错如下，请问是什么原因呢？
400 Bad Request
{"code":"PARAM_ERROR","detail":{"location":null,"value":["/query/sub_mch_id"]},"message":"请求中含有未在API文档中定义的参数"}

**Comment by as882301** [comment]
demo 都不搞全

**Comment by TheNorthMemory** [comment]
@as882301 

当你阅读了，[为 wechatpay-php 增加IDE提示的接口描述包 iwechatpay/openapi 介绍](https://developers.weixin.qq.com/community/develop/article/doc/000a0ce867842092f8cc65e5356013)，以及正确的使用了`composer`及成熟`IDE`，你会发现`demo`纯粹是多余的。

> 在 `PHPStorm` 及 `Visual Studio Code` 可正常链上几乎所有接口，请求参数描述也可以无脑式，从对应的方法中直接拷贝出去（没有任何方言的完整数据结构），当自有项目的数据接口参照。

**Comment by jk1860** [comment]
<br />
<b>Fatal error</b>:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.mch.weixin.qq.com/v3/certificates in D:\codes\eju_online\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211
Stack trace:
#0 D:\codes\eju_online\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(542): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 D:\codes\eju_online\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::retryFailedRewind(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Array)
#2 D:\codes\eju_online\vendor\guzzlehttp\guzzle\s in <b>D:\codes\eju_online\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php</b> on line <b>211</b><br />

搞不定阿，不知道什么情况~

**Comment by cmslz** [comment]
Builder::normalize 方法的替换兼容性不够好

**Comment by TheNorthMemory** [comment]
> Builder::normalize 方法的替换兼容性不够好

有没例子说明下不好在哪里？

**Comment by cmslz** [comment]
> 
![image](https://github.com/wechatpay-apiv3/wechatpay-php/assets/48888146/faefe3ee-0118-4e54-b657-55f1807b2f9b)
![image](https://github.com/wechatpay-apiv3/wechatpay-php/assets/48888146/7921f887-4c27-46bb-b7a5-ade0fc0e5afc)
Builder::normalize 方法把我的订单号替换了
我把截图圈起来的地方注释掉就可以正常查到订单结果了

**Comment by TheNorthMemory** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/48888146/256961407-faefe3ee-0118-4e54-b657-55f1807b2f9b.png) ![image](https://user-images.githubusercontent.com/48888146/256961438-7921f887-4c27-46bb-b7a5-ade0fc0e5afc.png) Builder::normalize 方法把我的订单号替换了 我把截图圈起来的地方注释掉就可以正常查到订单结果了

参考：

https://github.com/wechatpay-apiv3/wechatpay-php/issues/74#issuecomment-999283485

及README底部FAQ

### 为什么 URL 上的变量 OpenID，请求时被替换成小写了？

本 SDK 把 URL 中的大写视为包含连字号的 segment。请求时， camelCase 会替换为 camel-case。相关 issue 可参考 https://github.com/wechatpay-apiv3/wechatpay-php/issues/56、 https://github.com/wechatpay-apiv3/wechatpay-php/issues/69。

为了避免大小写错乱，URL 中存在变量时的正确做法是：使用 [链式 URI Template](https://github.com/wechatpay-apiv3/wechatpay-php#%E9%93%BE%E5%BC%8F-uri-template) 的 Path 变量。比如：

推荐写法 

```
->v3->marketing->favor->users->_openid_->coupons->post(['openid' => 'AbcdEF12345'])
->v3->marketing->favor->users->{'{openid}'}->coupons->post(['openid' => 'AbcdEF12345'])
->chain('{+myurl}')->post(['myurl' => 'v3/marketing/favor/users/AbcdEF12345/coupons'])
->{'{+myurl}'}->post(['myurl' => 'v3/marketing/favor/users/AbcdEF12345/coupons'])
```

**Comment by cmslz** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/48888146/256961407-faefe3ee-0118-4e54-b657-55f1807b2f9b.png) ![image](https://user-images.githubusercontent.com/48888146/256961438-7921f887-4c27-46bb-b7a5-ade0fc0e5afc.png) Builder::normalize 方法把我的订单号替换了 我把截图圈起来的地方注释掉就可以正常查到订单结果了
> 
> 参考：
> 
> [#74 (comment)](https://github.com/wechatpay-apiv3/wechatpay-php/issues/74#issuecomment-999283485)
> 
> 及README底部FAQ
> 
> ### 为什么 URL 上的变量 OpenID，请求时被替换成小写了？
> 本 SDK 把 URL 中的大写视为包含连字号的 segment。请求时， camelCase 会替换为 camel-case。相关 issue 可参考 #56 、 #69 。
> 
> 为了避免大小写错乱，URL 中存在变量时的正确做法是：使用 [链式 URI Template](https://github.com/wechatpay-apiv3/wechatpay-php#%E9%93%BE%E5%BC%8F-uri-template) 的 Path 变量。比如：
> 
> 推荐写法
> 
> ```
> ->v3->marketing->favor->users->_openid_->coupons->post(['openid' => 'AbcdEF12345'])
> ->v3->marketing->favor->users->{'{openid}'}->coupons->post(['openid' => 'AbcdEF12345'])
> ->chain('{+myurl}')->post(['myurl' => 'v3/marketing/favor/users/AbcdEF12345/coupons'])
> ->{'{+myurl}'}->post(['myurl' => 'v3/marketing/favor/users/AbcdEF12345/coupons'])
> ```

这个写法确实解决了我的问题,不过这种我之前那个用法很容易产生误导 还是感谢您的答复哈

**Comment by TheNorthMemory** [comment]
> > > > 
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/48888146/256961407-faefe3ee-0118-4e54-b657-55f1807b2f9b.png) ![image](https://user-images.githubusercontent.com/48888146/256961438-7921f887-4c27-46bb-b7a5-ade0fc0e5afc.png) Builder::normalize 方法把我的订单号替换了 我把截图圈起来的地方注释掉就可以正常查到订单结果了
> > 
> > 
> > 参考：
> > [#74 (comment)](https://github.com/wechatpay-apiv3/wechatpay-php/issues/74#issuecomment-999283485)
> > 及README底部FAQ
> > ### 为什么 URL 上的变量 OpenID，请求时被替换成小写了？
> > 本 SDK 把 URL 中的大写视为包含连字号的 segment。请求时， camelCase 会替换为 camel-case。相关 issue 可参考 #56 、 #69 。
> > 为了避免大小写错乱，URL 中存在变量时的正确做法是：使用 [链式 URI Template](https://github.com/wechatpay-apiv3/wechatpay-php#%E9%93%BE%E5%BC%8F-uri-template) 的 Path 变量。比如：
> > 推荐写法
> > ```
> > ->v3->marketing->favor->users->_openid_->coupons->post(['openid' => 'AbcdEF12345'])
> > ->v3->marketing->favor->users->{'{openid}'}->coupons->post(['openid' => 'AbcdEF12345'])
> > ->chain('{+myurl}')->post(['myurl' => 'v3/marketing/favor/users/AbcdEF12345/coupons'])
> > ->{'{+myurl}'}->post(['myurl' => 'v3/marketing/favor/users/AbcdEF12345/coupons'])
> > ```
> 
> 这个写法确实解决了我的问题,不过这种我之前那个用法很容易产生误导 还是感谢您的答复哈

语义化及参数化URL后，就可以大规模、批量、模式化去“描述”所谓的“资源”，建议再看看 https://github.com/TheNorthMemory/wechatpay-openapi 项目，800+业务请求描述，批量按此规则“约束描述”都生成出来了。

**Comment by shuizhangzhe** [comment]
微信支付平台证书下载报错
 [Symfony\Component\Process\Exception\ProcessTimedOutException]                              
  The process "git branch -a --no-color --no-abbrev -v" exceeded the timeout of 300 seconds.

**Comment by zhouyl** [comment]
1. 不提供沙箱账号申请，对开发不友好
2. 证书下载管理流程复杂、混乱，又要下载工具，又要登录这个登录那个，无法在一个页面完成全部操作
3. SDK DEMO和文档不完善，调试困难
总结：接过十多个支付方式，微信支付是最垃圾的

**Comment by c88667220** [comment]
麻烦问下，签名工具打不开是怎么回事？换几台电脑都不行
TenpayCertUtil,exe-应用程序错误
应用程序无法正常启动(0xc000007b)

还有我公众号可以支付，app调用一直显示签名错误，搞几天不知道错在哪，代码都一样的，平台证书和微信商户里面的证书到底该用哪个？有点混乱，支付宝那个三分钟就能搞好，你们这个好麻烦啊

**Comment by c88667220** [comment]
php 下载证书那块逻辑也有点奇怪，下载平台证书下面写个需要加载平台证书，这都没下载呢，从哪加载？

**Comment by van23qf** [comment]
对接支付这种流程多的，居然不提供沙箱测试，非要开发者拿真钱去调试？

**Comment by lo106258** [comment]
安装这个仓库或在线文档，你们谁能一步全走通的？

**Comment by houguang** [comment]
希望提供沙箱测试环境

**Comment by xnrcms** [comment]
这种sdk还是不要放出来了，写的乱七八糟

**Comment by xnrcms** [comment]
> 按照这个仓库或在线文档，你们谁能一步全走通的？

上传一直走不通

**Comment by DengSihan** [comment]
这个 issue 已经 4y+ 了，还不提供沙箱

开发体验/文档/sdk 比起 stripe 差太多了
